"""initial migration

Revision ID: 1ee217df8529
Revises: 
Create Date: 2025-03-16 19:08:14.337739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ee217df8529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_type', sa.Enum('ADMIN', 'USER', name='usertype'), server_default='USER', nullable=False),
    sa.Column('user_rank', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', 'MASTER', 'LEGENDARY', 'GODLIKE', name='userrank'), server_default='BEGINNER', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('post_id_table', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('post_images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('post_share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_post_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_post_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id_table')
    )
    op.create_table('comments',
    sa.Column('comment_id_table', sa.Integer(), nullable=False),
    sa.Column('post_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_comment_id'], ['posts.post_id_table'], ),
    sa.ForeignKeyConstraint(['user_comment_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id_table')
    )
    op.create_table('likes',
    sa.Column('likes_id_table', sa.Integer(), nullable=False),
    sa.Column('post_like_id', sa.Integer(), nullable=False),
    sa.Column('user_like_id', sa.Integer(), nullable=False),
    sa.Column('likes_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_like_id'], ['posts.post_id_table'], ),
    sa.ForeignKeyConstraint(['user_like_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('likes_id_table'),
    sa.UniqueConstraint('post_like_id', 'user_like_id', name='uix_post_user_like')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
