"""change column name

Revision ID: 307e11a509e0
Revises: 245d591339d0
Create Date: 2025-03-16 05:54:21.099668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '307e11a509e0'
down_revision: Union[str, None] = '245d591339d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_text', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('post_images', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('posts', sa.Column('post_share_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('created_post_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('updated_post_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('posts', 'images')
    op.drop_column('posts', 'text')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'share_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('share_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('posts', 'updated_post_at')
    op.drop_column('posts', 'created_post_at')
    op.drop_column('posts', 'post_share_count')
    op.drop_column('posts', 'post_images')
    op.drop_column('posts', 'post_text')
    # ### end Alembic commands ###
